apiVersion: v1
kind: Namespace
metadata:
  name: ntfy
  labels:
    name: ntfy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-deployment
  namespace: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
      - name: ntfy
        image: binwiederhier/ntfy:v2.15
        args: ["serve"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: http
        volumeMounts:
          - mountPath: /etc/ntfy
            name: ntfy-config
            readOnly: true
      volumes:
        - name: ntfy-config
          configMap:
            name: ntfy-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy-service
  namespace: ntfy
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    app: ntfy
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-ingress
  namespace: ntfy
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.13.0/24,10.8.0.0/24
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
      - ntfy.$DOMAIN
      secretName: ntfy-ingress-tls
  rules:
    - host: ntfy.$DOMAIN
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ntfy-service
              port:
                number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config-map
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.$DOMAIN
    behind-proxy: true
