apiVersion: v1
kind: Namespace
metadata:
  name: homepage
  labels:
    name: homepage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-pvc
  namespace: homepage
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-deployment
  namespace: homepage
spec:
  selector:
    matchLabels: &homepageLabels
      app.kubernetes.io/name: homepage
      app.kubernetes.io/component: homepage
  template:
    metadata:
      labels: *homepageLabels
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.$DOMAIN
            - name: LOG_TARGETS
              value: stdout
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/config
              name: homepage-storage
              subPath: config
      volumes:
        - name: homepage-storage
          persistentVolumeClaim:
            claimName: homepage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: homepage
spec:
  ports:
    - port: 3000
  selector: 
    app.kubernetes.io/name: homepage
    app.kubernetes.io/component: homepage 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.13.0/24
spec:
  tls:
    - hosts:
      - homepage.$DOMAIN
      secretName: homepage-ingress-tls
  rules:
    - host: homepage.$DOMAIN
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homepage-service
              port:
                number: 3000
