apiVersion: v2
name: odroid-platform
version: 1.2.0
dependencies:
  - name: cert-manager-dns-lexicon-webhook
    version: 1.0.0
    repository: file://../charts/cert-manager-dns-lexicon-webhook
    condition: cert-manager-dns-lexicon-webhook.enabled
  - name: longhorn
    version: 1.0.0
    repository: file://../charts/longhorn
    condition: longhorn.enabled
  - name: snapshot-controller
    version: 1.0.0
    repository: file://../charts/snapshot-controller
    condition: snapshot-controller.enabled
  - name: rustfs
    version: 1.0.0
    repository: file://../charts/rustfs
    condition: rustfs.enabled
  - name: velero
    version: 1.0.0
    repository: file://../charts/velero
    condition: velero.enabled
  - name: homepage
    version: 1.0.0
    repository: file://../charts/homepage
    condition: homepage.enabled
  - name: adguard
    version: 2.0.0
    repository: file://../charts/adguard
    condition: adguard.enabled
  - name: ntfy
    version: 1.0.0
    repository: file://../charts/ntfy
    condition: ntfy.enabled
  - name: actual
    version: 1.0.0
    repository: file://../charts/actual
    condition: actual.enabled
  - name: prometheus
    version: 1.0.0
    repository: file://../charts/prometheus
    condition: prometheus.enabled
  - name: grafana
    version: 1.0.0
    repository: file://../charts/grafana
    condition: grafana.enabled
  - name: loki
    version: 1.0.0
    repository: file://../charts/loki
    condition: loki.enabled
  - name: alloy
    version: 1.0.0
    repository: file://../charts/alloy
    condition: alloy.enabled