apiVersion: v1
kind: Namespace
metadata:
  name: adguard
  labels:
    name: adguard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-pvc
  namespace: adguard
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 750Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
  namespace: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      hostNetwork: true
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https-udp
              protocol: UDP
            - containerPort: 8443
              name: https-tcp
              protocol: TCP
            - containerPort: 67
              name: dhcp-udp
              protocol: UDP
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: adguard-storage
              subPath: config
            - mountPath: /opt/adguardhome/work
              name: adguard-storage
              subPath: work
      volumes:
        - name: adguard-storage
          persistentVolumeClaim:
            claimName: adguard-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: adguard
spec:
  type: LoadBalancer 
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: http
      port: 8080
      protocol: TCP
    - name: https
      port: 8443
      protocol: TCP
    - name: dhcp
      port: 67
      protocol: UDP
  selector: 
    app: adguard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-ingress
  namespace: adguard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.13.0/24,10.8.0.0/24
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
      - adguard.$DOMAIN
      secretName: adguard-ingress-tls
  rules:
    - host: adguard.$DOMAIN
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: adguard-service
              port:
                number: 8080
