{{- if .Values.prometheusExporter.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adguard-prometheus-exporter.fullname" . }}
  namespace: {{ include "adguard.namespace" . }}
  labels:
    {{- include "adguard-prometheus-exporter.labels" . | nindent 4 }}
stringData:
  ADGUARD_PASSWORDS: {{ join "," .Values.prometheusExporter.passwords }}
{{- end }}