apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actual.fullname" . }}
  namespace: {{ include "actual.namespace" . }}
  labels:
    {{- include "actual.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "actual.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "actual.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ACTUAL_PORT
              value: {{ .Values.service.port | quote }}
            {{- with .Values.config.trustedProxies }}
            - name: ACTUAL_TRUSTED_PROXIES
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.config.uploadFileSizeLimitMb }}
            - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.data.enabled }}
          volumeMounts:
            - mountPath: /data
              name: actual-storage-data
          {{- end }}
      {{- if .Values.persistence.data.enabled }}
      volumes:
        - name: actual-storage-data
          persistentVolumeClaim:
            claimName: {{ include "actual.fullname" . }}-data
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
