{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        webhook:
          groupName: {{ .Values.clusterIssuer.webhook.groupName }}
          solverName: lexicon
          config:
            provider: {{ .Values.clusterIssuer.webhook.provider }}
            ttl: {{ .Values.clusterIssuer.webhook.ttl }}
            usePassword: true
            apiKeyRef:
              name: {{ .Values.clusterIssuer.secret.name }}
              key: auth_username
            apiSecretRef:
              name: {{ .Values.clusterIssuer.secret.name }}
              key: auth_password
{{- end }}