apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  # form Monday through Saturday
  cron: "0 2 * * 1-6"
  task: "backup"
  retain: 7
  concurrency: 2
  groups:
    - gfs-backup
  labels:
    backup-type: daily
  parameters:
    full-backup-interval: "0"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  # every Sunday
  cron: "0 2 * * 0"
  task: "backup"
  retain: 4
  concurrency: 2
  groups:
    - gfs-backup
  labels:
    backup-type: weekly
  parameters:
    full-backup-interval: "0"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-monthly-full
  namespace: longhorn
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
spec:
  cron: "0 3 1 * *"
  task: "backup"
  retain: 3
  concurrency: 1
  groups:
    - gfs-backup
  labels:
    backup-type: monthly
    backup-class: full
  parameters:
    full-backup-interval: "1"