apiVersion: v2
name: grafana
description: Grafana – observability and data visualization platform.
type: application
version: 1.0.0
dependencies:
  - name: grafana
    version: 13.2.5
    repository: https://grafana-community.github.io/helm-charts
